name: Deploy Next.js ComercialQuality
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npm install -g pnpm pm2
          npx pnpm install
        shell: powershell

      - name: Build Project
        run: npx pnpm run build
        shell: powershell

      - name: Deploy to IIS Folder
        run: |
          $sourcePath = "."
          $destinationPath = "C:\inetpub\wwwroot\NextQuality"
          robocopy $sourcePath $destinationPath /MIR /V /NP /XD node_modules .git .github /XF .env .env.local web.config ecosystem.config.js
          if ($lastexitcode -lt 8) { exit 0 } else { exit $lastexitcode }
        shell: powershell

      - name: Restart App with PM2
        run: |
          $ErrorActionPreference = "SilentlyContinue"
          npx pm2 delete "comercial-quality" | Out-Null
          $ErrorActionPreference = "Stop"

          cd "C:\inetpub\wwwroot\NextQuality"
          npx pm2 start ecosystem.config.js
          npx pm2 save
        shell: powershell
